'''
Colors of the app
'''

INVALID_VALUE = '#FF82AB'
VALID_VALUE = '#90EE90'
NOT_MATCH = '#FF82AB'

WEAK_STRENGTH_PASSWORD = '#CD5C5C'
MIDDLE_STRENGTH_PASSWORD = '#FFD700'
STRONG__STRENGTH_PASSWORD = '#90EE90'
